### PR TITLE
feat: vscode plugin format

### PR DESCRIPTION
**Pull request by Eomm**
This code should let us to publish the snippets as a VSCode plugin but I need support to publish as `fastify` since there are some steps to do it:

https://code.visualstudio.com/api/working-with-extensions/publishing-extension

Moreover @zekth pointed out the we should rename the repo/project as `fastify-snippets` or simply `vscode-snippets`  I would propopose

@mcollina

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

what do you need? An account on Azure DevOps?

**Review by zekth — APPROVED** [review]
lgtm

**Comment by Eomm** [comment]
> lgtm
> 
> what do you need? An account on Azure DevOps?

I was able to do it tho..

I have created the publisher: https://marketplace.visualstudio.com/manage/publishers/fastify
but I cannot invite you as owner: 

image

Maybe do you have another email for the Azure DevOps site?

I have added the logo, now I should be able to publish it!

**Comment by mcollina** [comment]
I have no clue, that emails should work.

You can also try hello@matteocollina.com.

**Comment by Eomm** [comment]
> I have no clue, that emails should work.
> 
> You can also try [hello@matteocollina.com](mailto:hello@matteocollina.com).

Nope, I will try to contact the support

**Pull request merged**
